name: mrbromley
favicon: null
layout_spectrum: 0.3059139237739146
typography_spectrum: 0.5491031259298325
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4073420697823167
  lightness: 0.37179718958213925
  saturation: 0.5877076904289424
  rhythmicContrast: 0.468858455773443
purpose: []
